# Generated by Django 4.2.7 on 2026-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
