# Generated by Django 6.0.6 on 2026-07-06 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(help_text='Journal entry text content (transcribed if voice entry)')),
                ('is_voice', models.BooleanField(default=False, help_text='Designates if this entry was captured via voice recording.')),
                ('analysis', models.JSONField(blank=True, default=dict, help_text='AI Analysis containing sentiment indicators and themes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
