# Generated by Django 6.0.6 on 2026-07-06 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(help_text='Actual duration user completed the exercise in minutes')),
                ('satisfaction', models.IntegerField(help_text='Satisfaction rating from 1 to 5')),
                ('mood_improved', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapyActivity',
            fields=[
                ('id', models.CharField(help_text="Unique slug (e.g. 'act-1') matching frontend constants", max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='E.g. Mindfulness, Cognitive, Somatic', max_length=100)),
                ('duration', models.CharField(help_text="E.g. '10 min', '5 min'", max_length=50)),
                ('difficulty', models.CharField(help_text='E.g. Simple, Moderate', max_length=50)),
                ('description', models.TextField()),
                ('instructions', models.JSONField(default=list, help_text='Step-by-step array of instructions for user to follow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Therapy Activities',
            },
        ),
    ]
