# Generated by Django 6.0.8 on 2026-08-06 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyactivity',
            name='contraindications',
            field=models.JSONField(blank=True, default=list, help_text='List of conditions where this should NOT be recommended'),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='emotions',
            field=models.JSONField(blank=True, default=list, help_text='List of matching emotions'),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='estimated_time',
            field=models.IntegerField(default=5, help_text='Estimated duration in minutes for sorting'),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='interactive_type',
            field=models.CharField(default='static', help_text='E.g., breathing, meditation, cognitive', max_length=50),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='mood_range',
            field=models.JSONField(blank=True, default=list, help_text='List of recommended mood levels [min, max]'),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='stress_range',
            field=models.JSONField(blank=True, default=list, help_text='List of stress levels [min, max]'),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='List of matching journal topics/themes'),
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='started', help_text='started, completed, skipped, cancelled', max_length=20)),
                ('mood_before', models.IntegerField(blank=True, null=True)),
                ('mood_after', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Secs spent in the interactive session')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.therapyactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
