# Generated by Django 6.0.8 on 2026-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_therapyactivity_contraindications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityfeedback',
            name='mood_after',
            field=models.IntegerField(blank=True, help_text='1-10 scale', null=True),
        ),
        migrations.AddField(
            model_name='activityfeedback',
            name='stress_after',
            field=models.IntegerField(blank=True, help_text='1-10 scale', null=True),
        ),
    ]
