# Generated by Django 6.0.8 on 2026-08-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activityfeedback_comment_activityfeedback_mood_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyactivity',
            name='agg_avg_improvement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='agg_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='agg_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='therapyactivity',
            name='agg_total_recommendations',
            field=models.IntegerField(default=0),
        ),
    ]
