# Generated by Django 6.0.6 on 2026-07-06 13:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mood', models.IntegerField(help_text='Mood score from 1 (lowest) to 5 (highest)')),
                ('mood_label', models.CharField(max_length=50)),
                ('stress', models.IntegerField(help_text='Stress score from 0 (calm) to 10 (stressed)')),
                ('energy', models.IntegerField(help_text='Energy and focus score from 0 to 10')),
                ('sleep', models.DecimalField(decimal_places=2, help_text='Sleeptime duration in hours', max_digits=4)),
                ('productivity', models.IntegerField(help_text='Productivity score from 0 to 10')),
                ('social', models.IntegerField(help_text='Social connection score from 0 to 10')),
                ('notes', models.TextField(blank=True, help_text='Optional daily notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
