# Generated by Django 6.0.6 on 2026-08-07 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', 'date'], name='moodlog_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='moodlog',
            index=models.Index(fields=['user', '-date'], name='moodlog_user_date_desc_idx'),
        ),
    ]
