# Generated by Django 6.0.6 on 2026-07-06 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why this activity was suggested (explain fit profile context)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current recommendation shown on the dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='activities.therapyactivity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
