# Generated by Django 6.0.6 on 2026-07-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Confidence percentage float', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='improvement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='journal_theme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='mood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='mood_after',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='mood_before',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reasons_list',
            field=models.JSONField(blank=True, default=list, help_text='Bulleted list of personalized matches'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(blank=True, help_text='Recommendation raw calculated score', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='stress',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='trigger',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
