# Generated by Django 6.0.6 on 2026-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_recommendation_completed_recommendation_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='historical_matches',
            field=models.IntegerField(default=0, help_text='Number of historical theme-matching journals'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='mood_improvement',
            field=models.CharField(blank=True, help_text='Mood improvement description string', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='rec_type',
            field=models.CharField(choices=[('quick', 'Quick'), ('complete', 'Complete')], default='complete', help_text='Type of recommendation (quick or complete)', max_length=15),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='success_rate',
            field=models.CharField(blank=True, help_text='Historical activity success rate percentage string', max_length=50, null=True),
        ),
    ]
