# Generated by Django 6.0.6 on 2026-08-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_recommendation_historical_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='daily_suggestion',
            field=models.TextField(blank=True, help_text='AI-style coach daily suggestion/insight', null=True),
        ),
    ]
