# Generated by Django 6.0.7 on 2026-08-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_recommendation_daily_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='daily_suggestion',
        ),
    ]
