# Generated by Django 6.0.7 on 2026-08-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_remove_recommendation_daily_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='daily_suggestion',
            field=models.TextField(blank=True, help_text='AI-style coach daily suggestion/insight', null=True),
        ),
    ]
