# Generated by Django 6.0.6 on 2026-08-07 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_therapyactivity_agg_avg_improvement_and_more'),
        ('recommendation', '0007_recommendation_daily_suggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'is_active'], name='rec_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'created_at'], name='rec_user_created_idx'),
        ),
    ]
