# Generated by Django 6.0.6 on 2026-07-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='voice_preference',
            field=models.CharField(default='not_selected', max_length=50),
        ),
    ]
