# Generated by Django 6.0.6 on 2026-07-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_voice_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='voice_preference',
            field=models.CharField(default='calm-female', max_length=50),
        ),
    ]
