# Generated by Django 6.0.7 on 2026-08-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_voice_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trigger_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
