# Generated by Django 6.0.6 on 2026-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_voice_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wellness_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
