# Generated by Django 6.0.6 on 2026-08-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_wellness_score'),
        ('users', '0006_userprofile_trigger_keywords'),
    ]

    operations = [
    ]
