# Generated by Django 6.0.6 on 2026-07-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisalert',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='The journal entry that triggered this crisis alert, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crisis_alerts', to='journal.journalentry'),
        ),
    ]
